# Initialize all submodules; emulates git clone --recursive
os: unstable

install:
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 12 2013"

build:
  project: aseprite.sln

# Build fails if one job fails
matrix:
  fast_finish: true

artifacts:
  - path: bin/aseprite.exe
