os: Visual Studio 2015 RC

# Initialize all submodules; emulates git clone --recursive
install:
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 12 2013"

build:
  project: aseprite.sln

# Build fails if one job fails
matrix:
  fast_finish: true

artifacts:
  - path: bin/aseprite.exe
  - path: \*.sln
  - path: \*.vcxproj
  - path: \*.vcxproj.filters
  - path: CMake*
  - path: cmake*
