# Initialize all submodules; emulates git clone --recursive
install:
  - git submodule update --init --recursive
  - SET PATH=C:\Program Files (x86)\Microsoft DirectX SDK;%PATH%

before_build:
  - cmake -G "Visual Studio 12 2013"

platform: x86

build:
  project: aseprite.sln

# Build fails if one job fails
matrix:
  fast_finish: true

artifacts:
  - path: bin/aseprite.exe
